/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * @minItems 1
 */
export type CoordinateTransformations = [
  (
    | {
        type: "scale";
        /**
         * @minItems 2
         */
        scale: [number, number, ...number[]];
        [k: string]: unknown;
      }
    | {
        type: "translation";
        /**
         * @minItems 2
         */
        translation: [number, number, ...number[]];
        [k: string]: unknown;
      }
  ),
  ...(
    | {
        type: "scale";
        /**
         * @minItems 2
         */
        scale: [number, number, ...number[]];
        [k: string]: unknown;
      }
    | {
        type: "translation";
        /**
         * @minItems 2
         */
        translation: [number, number, ...number[]];
        [k: string]: unknown;
      }
  )[]
];
/**
 * @minItems 2
 * @maxItems 5
 */
export type Axes =
  | [
      (
        | {
            name: string;
            type: "channel" | "time" | "space";
            [k: string]: unknown;
          }
        | {
            name: string;
            type?: string;
            [k: string]: unknown;
          }
      ),
      (
        | {
            name: string;
            type: "channel" | "time" | "space";
            [k: string]: unknown;
          }
        | {
            name: string;
            type?: string;
            [k: string]: unknown;
          }
      )
    ]
  | [
      (
        | {
            name: string;
            type: "channel" | "time" | "space";
            [k: string]: unknown;
          }
        | {
            name: string;
            type?: string;
            [k: string]: unknown;
          }
      ),
      (
        | {
            name: string;
            type: "channel" | "time" | "space";
            [k: string]: unknown;
          }
        | {
            name: string;
            type?: string;
            [k: string]: unknown;
          }
      ),
      (
        | {
            name: string;
            type: "channel" | "time" | "space";
            [k: string]: unknown;
          }
        | {
            name: string;
            type?: string;
            [k: string]: unknown;
          }
      )
    ]
  | [
      (
        | {
            name: string;
            type: "channel" | "time" | "space";
            [k: string]: unknown;
          }
        | {
            name: string;
            type?: string;
            [k: string]: unknown;
          }
      ),
      (
        | {
            name: string;
            type: "channel" | "time" | "space";
            [k: string]: unknown;
          }
        | {
            name: string;
            type?: string;
            [k: string]: unknown;
          }
      ),
      (
        | {
            name: string;
            type: "channel" | "time" | "space";
            [k: string]: unknown;
          }
        | {
            name: string;
            type?: string;
            [k: string]: unknown;
          }
      ),
      (
        | {
            name: string;
            type: "channel" | "time" | "space";
            [k: string]: unknown;
          }
        | {
            name: string;
            type?: string;
            [k: string]: unknown;
          }
      )
    ]
  | [
      (
        | {
            name: string;
            type: "channel" | "time" | "space";
            [k: string]: unknown;
          }
        | {
            name: string;
            type?: string;
            [k: string]: unknown;
          }
      ),
      (
        | {
            name: string;
            type: "channel" | "time" | "space";
            [k: string]: unknown;
          }
        | {
            name: string;
            type?: string;
            [k: string]: unknown;
          }
      ),
      (
        | {
            name: string;
            type: "channel" | "time" | "space";
            [k: string]: unknown;
          }
        | {
            name: string;
            type?: string;
            [k: string]: unknown;
          }
      ),
      (
        | {
            name: string;
            type: "channel" | "time" | "space";
            [k: string]: unknown;
          }
        | {
            name: string;
            type?: string;
            [k: string]: unknown;
          }
      ),
      (
        | {
            name: string;
            type: "channel" | "time" | "space";
            [k: string]: unknown;
          }
        | {
            name: string;
            type?: string;
            [k: string]: unknown;
          }
      )
    ];

/**
 * JSON from OME-NGFF .zattrs
 */
export interface NGFFImage {
  /**
   * The multiscale datasets for this image
   *
   * @minItems 1
   */
  multiscales: [
    {
      name?: string;
      /**
       * @minItems 1
       */
      datasets: [
        {
          path: string;
          coordinateTransformations: CoordinateTransformations;
          [k: string]: unknown;
        },
        ...{
          path: string;
          coordinateTransformations: CoordinateTransformations;
          [k: string]: unknown;
        }[]
      ];
      version?: "0.4";
      axes: Axes;
      coordinateTransformations?: CoordinateTransformations;
      [k: string]: unknown;
    },
    ...{
      name?: string;
      /**
       * @minItems 1
       */
      datasets: [
        {
          path: string;
          coordinateTransformations: CoordinateTransformations;
          [k: string]: unknown;
        },
        ...{
          path: string;
          coordinateTransformations: CoordinateTransformations;
          [k: string]: unknown;
        }[]
      ];
      version?: "0.4";
      axes: Axes;
      coordinateTransformations?: CoordinateTransformations;
      [k: string]: unknown;
    }[]
  ];
  omero?: {
    channels: {
      window: {
        end: number;
        max: number;
        min: number;
        start: number;
        [k: string]: unknown;
      };
      label?: string;
      family?: string;
      color: string;
      active?: boolean;
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
