/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * JSON from OME-NGFF .zattrs
 */
export interface OMENGFFLabelledImageSchema {
  "image-label"?: {
    /**
     * The colors for this label image
     *
     * @minItems 1
     */
    colors?: [
      {
        /**
         * The value of the label
         */
        "label-value": number;
        /**
         * The RGBA color stored as an array of four integers between 0 and 255
         *
         * @minItems 4
         * @maxItems 4
         */
        rgba?: [number, number, number, number];
        [k: string]: unknown;
      },
      ...{
        /**
         * The value of the label
         */
        "label-value": number;
        /**
         * The RGBA color stored as an array of four integers between 0 and 255
         *
         * @minItems 4
         * @maxItems 4
         */
        rgba?: [number, number, number, number];
        [k: string]: unknown;
      }[]
    ];
    /**
     * The properties for this label image
     *
     * @minItems 1
     */
    properties?: [
      {
        /**
         * The pixel value for this label
         */
        "label-value": number;
        [k: string]: unknown;
      },
      ...{
        /**
         * The pixel value for this label
         */
        "label-value": number;
        [k: string]: unknown;
      }[]
    ];
    /**
     * The source of this label image
     */
    source?: {
      image?: string;
      [k: string]: unknown;
    };
    /**
     * The version of the specification
     */
    version?: "0.4";
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
