/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * JSON from OME-NGFF OME/.zattrs linked to an OME-XML file
 */
export interface NGFFGroupProducedByBioformats2RawToContainOMEMetadata {
  /**
   * An array of the same length and the same order as the images defined in the OME-XML
   */
  series?: string[];
  [k: string]: unknown;
}
