/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * JSON from OME-NGFF .zattrs
 */
export interface OMENGFFPlateSchema {
  plate?: {
    /**
     * The acquisitions for this plate
     */
    acquisitions?: {
      /**
       * A unique identifier within the context of the plate
       */
      id: number;
      /**
       * The maximum number of fields of view for the acquisition
       */
      maximumfieldcount?: number;
      /**
       * The name of the acquisition
       */
      name?: string;
      /**
       * The description of the acquisition
       */
      description?: string;
      /**
       * The start timestamp of the acquisition, expressed as epoch time i.e. the number seconds since the Epoch
       */
      starttime?: number;
      /**
       * The end timestamp of the acquisition, expressed as epoch time i.e. the number seconds since the Epoch
       */
      endtime?: number;
      [k: string]: unknown;
    }[];
    /**
     * The version of the specification
     */
    version?: "0.4";
    /**
     * The maximum number of fields per view across all wells
     */
    field_count?: number;
    /**
     * The name of the plate
     */
    name?: string;
    /**
     * The columns of the plate
     *
     * @minItems 1
     */
    columns: [
      {
        /**
         * The column name
         */
        name: string;
        [k: string]: unknown;
      },
      ...{
        /**
         * The column name
         */
        name: string;
        [k: string]: unknown;
      }[]
    ];
    /**
     * The rows of the plate
     *
     * @minItems 1
     */
    rows: [
      {
        /**
         * The row name
         */
        name: string;
        [k: string]: unknown;
      },
      ...{
        /**
         * The row name
         */
        name: string;
        [k: string]: unknown;
      }[]
    ];
    /**
     * The wells of the plate
     *
     * @minItems 1
     */
    wells: [
      {
        /**
         * The path to the well subgroup
         */
        path: string;
        /**
         * The index of the well in the rows list
         */
        rowIndex: number;
        /**
         * The index of the well in the columns list
         */
        columnIndex: number;
        [k: string]: unknown;
      },
      ...{
        /**
         * The path to the well subgroup
         */
        path: string;
        /**
         * The index of the well in the rows list
         */
        rowIndex: number;
        /**
         * The index of the well in the columns list
         */
        columnIndex: number;
        [k: string]: unknown;
      }[]
    ];
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
