/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * JSON from OME-NGFF .zattrs
 */
export interface OMENGFFWellSchema {
  well?: {
    /**
     * The fields of view for this well
     *
     * @minItems 1
     */
    images: [
      {
        /**
         * A unique identifier within the context of the plate
         */
        acquisition?: number;
        /**
         * The path for this field of view subgroup
         */
        path: string;
        [k: string]: unknown;
      },
      ...{
        /**
         * A unique identifier within the context of the plate
         */
        acquisition?: number;
        /**
         * The path for this field of view subgroup
         */
        path: string;
        [k: string]: unknown;
      }[],
    ];
    /**
     * The version of the specification
     */
    version?: "0.4";
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
