/**
 * ATTENTION. This code was AUTO GENERATED by schema2typebox.
 * While I don't know your use case, there is a high chance that direct changes
 * to this file get lost. Consider making changes to the underlying JSON schema
 * you use to generate this file instead. The default file is called
 * "schema.json", perhaps have a look there! :]
 */

import {
  Kind,
  SchemaOptions,
  Static,
  TSchema,
  TUnion,
  Type,
  TypeRegistry,
} from "@sinclair/typebox";
import { Value } from "@sinclair/typebox/value";

TypeRegistry.Set(
  "ExtendedOneOf",
  (schema: any, value) =>
    1 ===
    schema.oneOf.reduce(
      (acc: number, schema: any) => acc + (Value.Check(schema, value) ? 1 : 0),
      0
    )
);

const OneOf = <T extends TSchema[]>(
  oneOf: [...T],
  options: SchemaOptions = {}
) =>
  Type.Unsafe<Static<TUnion<T>>>({
    ...options,
    [Kind]: "ExtendedOneOf",
    oneOf,
  });

export type OmeZarrImage = Static<typeof OmeZarrImage>;
export const OmeZarrImage = Type.Object(
  {
    ome: Type.Object(
      {
        multiscales: Type.Array(
          Type.Object({
            name: Type.Optional(Type.String()),
            datasets: Type.Array(
              Type.Object({
                path: Type.String(),
                coordinateTransformations: Type.Array(
                  OneOf([
                    Type.Object({
                      type: Type.Union([Type.Literal("scale")]),
                      scale: Type.Array(Type.Number(), { minItems: 2 }),
                    }),
                    Type.Object({
                      type: Type.Union([Type.Literal("translation")]),
                      translation: Type.Array(Type.Number(), { minItems: 2 }),
                    }),
                  ]),
                  {
                    minItems: 1,
                    contains: {
                      type: "object",
                      properties: {
                        type: { type: "string", enum: ["scale"] },
                        scale: {
                          type: "array",
                          minItems: 2,
                          items: { type: "number" },
                        },
                      },
                    },
                    maxContains: 1,
                  }
                ),
              }),
              { minItems: 1 }
            ),
            axes: Type.Array(
              OneOf([
                Type.Object({
                  name: Type.String(),
                  type: Type.Union([
                    Type.Literal("channel"),
                    Type.Literal("time"),
                    Type.Literal("space"),
                  ]),
                }),
                Type.Object({
                  name: Type.String(),
                  type: Type.Optional(
                    Type.Not(
                      Type.Union([
                        Type.Literal("space"),
                        Type.Literal("time"),
                        Type.Literal("channel"),
                      ])
                    )
                  ),
                }),
              ]),
              {
                uniqueItems: true,
                minItems: 2,
                maxItems: 5,
                contains: {
                  type: "object",
                  properties: {
                    name: { type: "string" },
                    type: { type: "string", enum: ["space"] },
                    unit: { type: "string" },
                  },
                },
                minContains: 2,
                maxContains: 3,
              }
            ),
            coordinateTransformations: Type.Optional(
              Type.Array(
                OneOf([
                  Type.Object({
                    type: Type.Union([Type.Literal("scale")]),
                    scale: Type.Array(Type.Number(), { minItems: 2 }),
                  }),
                  Type.Object({
                    type: Type.Union([Type.Literal("translation")]),
                    translation: Type.Array(Type.Number(), { minItems: 2 }),
                  }),
                ]),
                {
                  minItems: 1,
                  contains: {
                    type: "object",
                    properties: {
                      type: { type: "string", enum: ["scale"] },
                      scale: {
                        type: "array",
                        minItems: 2,
                        items: { type: "number" },
                      },
                    },
                  },
                  maxContains: 1,
                }
              )
            ),
          }),
          {
            description: "The multiscale datasets for this image",
            minItems: 1,
            uniqueItems: true,
          }
        ),
        omero: Type.Optional(
          Type.Object({
            channels: Type.Array(
              Type.Object({
                window: Type.Optional(
                  Type.Object({
                    end: Type.Number(),
                    max: Type.Number(),
                    min: Type.Number(),
                    start: Type.Number(),
                  })
                ),
                label: Type.Optional(Type.String()),
                family: Type.Optional(Type.String()),
                color: Type.Optional(Type.String()),
                active: Type.Optional(Type.Boolean()),
              })
            ),
          })
        ),
        version: Type.Union([Type.Literal("0.5")], {
          $schema: "https://json-schema.org/draft/2020-12/schema",
          $id: "https://ngff.openmicroscopy.org/0.5/schemas/_version.schema",
          description: "The version of the OME-Zarr Metadata",
        }),
      },
      { description: "The versioned OME-Zarr Metadata namespace" }
    ),
  },
  {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    $id: "https://ngff.openmicroscopy.org/0.5/schemas/image.schema",
    description: "The zarr.json attributes key",
    $defs: {
      multiscales: {
        description: "The multiscale datasets for this image",
        type: "array",
        items: {
          type: "object",
          properties: {
            name: { type: "string" },
            datasets: {
              type: "array",
              minItems: 1,
              items: {
                type: "object",
                properties: {
                  path: { type: "string" },
                  coordinateTransformations: {
                    type: "array",
                    minItems: 1,
                    contains: {
                      type: "object",
                      properties: {
                        type: { type: "string", enum: ["scale"] },
                        scale: {
                          type: "array",
                          minItems: 2,
                          items: { type: "number" },
                        },
                      },
                    },
                    maxContains: 1,
                    items: {
                      oneOf: [
                        {
                          type: "object",
                          properties: {
                            type: { type: "string", enum: ["scale"] },
                            scale: {
                              type: "array",
                              minItems: 2,
                              items: { type: "number" },
                            },
                          },
                          required: ["type", "scale"],
                        },
                        {
                          type: "object",
                          properties: {
                            type: { type: "string", enum: ["translation"] },
                            translation: {
                              type: "array",
                              minItems: 2,
                              items: { type: "number" },
                            },
                          },
                          required: ["type", "translation"],
                        },
                      ],
                    },
                  },
                },
                required: ["path", "coordinateTransformations"],
              },
            },
            axes: {
              type: "array",
              uniqueItems: true,
              minItems: 2,
              maxItems: 5,
              contains: {
                type: "object",
                properties: {
                  name: { type: "string" },
                  type: { type: "string", enum: ["space"] },
                  unit: { type: "string" },
                },
              },
              minContains: 2,
              maxContains: 3,
              items: {
                oneOf: [
                  {
                    type: "object",
                    properties: {
                      name: { type: "string" },
                      type: {
                        type: "string",
                        enum: ["channel", "time", "space"],
                      },
                    },
                    required: ["name", "type"],
                  },
                  {
                    type: "object",
                    properties: {
                      name: { type: "string" },
                      type: {
                        type: "string",
                        not: { enum: ["space", "time", "channel"] },
                      },
                    },
                    required: ["name"],
                  },
                ],
              },
            },
            coordinateTransformations: {
              type: "array",
              minItems: 1,
              contains: {
                type: "object",
                properties: {
                  type: { type: "string", enum: ["scale"] },
                  scale: {
                    type: "array",
                    minItems: 2,
                    items: { type: "number" },
                  },
                },
              },
              maxContains: 1,
              items: {
                oneOf: [
                  {
                    type: "object",
                    properties: {
                      type: { type: "string", enum: ["scale"] },
                      scale: {
                        type: "array",
                        minItems: 2,
                        items: { type: "number" },
                      },
                    },
                    required: ["type", "scale"],
                  },
                  {
                    type: "object",
                    properties: {
                      type: { type: "string", enum: ["translation"] },
                      translation: {
                        type: "array",
                        minItems: 2,
                        items: { type: "number" },
                      },
                    },
                    required: ["type", "translation"],
                  },
                ],
              },
            },
          },
          required: ["datasets", "axes"],
        },
        minItems: 1,
        uniqueItems: true,
      },
      omero: {
        type: "object",
        properties: {
          channels: {
            type: "array",
            items: {
              type: "object",
              properties: {
                window: {
                  type: "object",
                  properties: {
                    end: { type: "number" },
                    max: { type: "number" },
                    min: { type: "number" },
                    start: { type: "number" },
                  },
                  required: ["start", "min", "end", "max"],
                },
                label: { type: "string" },
                family: { type: "string" },
                color: { type: "string" },
                active: { type: "boolean" },
              },
            },
          },
        },
        required: ["channels"],
      },
      axes: {
        type: "array",
        uniqueItems: true,
        minItems: 2,
        maxItems: 5,
        contains: {
          type: "object",
          properties: {
            name: { type: "string" },
            type: { type: "string", enum: ["space"] },
            unit: { type: "string" },
          },
        },
        minContains: 2,
        maxContains: 3,
        items: {
          oneOf: [
            {
              type: "object",
              properties: {
                name: { type: "string" },
                type: { type: "string", enum: ["channel", "time", "space"] },
              },
              required: ["name", "type"],
            },
            {
              type: "object",
              properties: {
                name: { type: "string" },
                type: {
                  type: "string",
                  not: { enum: ["space", "time", "channel"] },
                },
              },
              required: ["name"],
            },
          ],
        },
      },
      coordinateTransformations: {
        type: "array",
        minItems: 1,
        contains: {
          type: "object",
          properties: {
            type: { type: "string", enum: ["scale"] },
            scale: { type: "array", minItems: 2, items: { type: "number" } },
          },
        },
        maxContains: 1,
        items: {
          oneOf: [
            {
              type: "object",
              properties: {
                type: { type: "string", enum: ["scale"] },
                scale: {
                  type: "array",
                  minItems: 2,
                  items: { type: "number" },
                },
              },
              required: ["type", "scale"],
            },
            {
              type: "object",
              properties: {
                type: { type: "string", enum: ["translation"] },
                translation: {
                  type: "array",
                  minItems: 2,
                  items: { type: "number" },
                },
              },
              required: ["type", "translation"],
            },
          ],
        },
      },
    },
  }
);
